title: Mind Patch
description: "I share some security blogs here"
author:
  name: "MindPatch"
  email: "his@mindpatch.net"
  url: "https://mindpatch.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Mindpatch"
year : "2025"
