name: Build Blog Posts

on:
  push:
    branches: [ main, master ]
    paths: 
      - 'posts/**/*.md'
      - 'app/**/*'
      - 'lib/**/*'
      - 'scripts/**/*'
  pull_request:
    branches: [ main, master ]
    paths: 
      - 'posts/**/*.md'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-blog:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Generate blog posts from markdown
      run: node scripts/generate-blog-posts.mjs

    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add lib/blog-posts.ts
        git commit -m "🤖 Auto-generate blog posts from markdown files" || exit 0
        git push

    - name: Build Next.js application
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./out

  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: build-blog
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4 